services:
  - type: static_site
    name: krayonova
    region: oregon
    buildCommand: npm install && npm run build && npm run export
    staticPublishPath: out
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
